name: start9-registry
version: 0.2.0

default-extensions:
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - StandaloneDeriving

dependencies:
  - base >=4.12 && <5
  - base64
  - aeson
  - ansi-terminal
  - attoparsec
  - bytestring
  - casing
  - can-i-haz
  - conduit
  - conduit-extra
  - containers
  - cryptonite
  - cryptonite-conduit
  - data-default
  - directory
  - errors
  - esqueleto
  - extra
  - file-embed
  - fast-logger
  - filepath
  - foreign-store
  - fsnotify
  - http-api-data
  - http-types
  - interpolate
  - lens
  - memory
  - monad-logger
  - monad-logger-extras
  - monad-loops
  - parallel
  - persistent
  - persistent-migration
  - persistent-postgresql
  - persistent-template
  - process
  - protolude
  - shakespeare
  - template-haskell
  - text
  - time
  - transformers
  - typed-process
  - unliftio
  - unordered-containers
  - unix
  - wai
  - wai-cors
  - wai-extra
  - warp
  - warp-tls
  - yaml
  - yesod
  - yesod-auth
  - yesod-auth-basic
  - yesod-core
  - yesod-persistent

library:
  source-dirs: src
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        cpp-options: -DDEVELOPMENT
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O0
          - -fdefer-typed-holes
      else:
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O2
          - -fdefer-typed-holes

executables:
  start9-registry:
    source-dirs: app
    main: main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fdefer-typed-holes
    dependencies:
      - start9-registry
    when:
      - condition: flag(library-only)
        buildable: false
  embassy-publish:
    source-dirs: cli
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fdefer-typed-holes
    dependencies:
      - start9-registry
    when:
      - condition: flag(library-only)
        buildable: false
tests:
  start9-registry-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -fdefer-typed-holes
    dependencies:
      - start9-registry
      - hspec
      - yesod-test
      - hedgehog

flags:
  library-only:
    manual: false
    default: false
    description: Build for use with "yesod devel"
  dev:
    manual: false
    default: false
    description: Turn on development settings, like auto-reload templates.
